[build]
  command = "npm run build"
  publish = "."

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build.environment]
  NODE_VERSION = "16"
