[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "axios"]
  included_files = ["temp/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/sub"
  to = "/.netlify/functions/index/sub"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"

[build.environment]
  NODE_VERSION = "16"